/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:db-schema` to regenerate this file.
 */

import type {} from '@payloadcms/db-postgres'
import {
  pgTable,
  index,
  uniqueIndex,
  foreignKey,
  integer,
  varchar,
  timestamp,
  serial,
  boolean,
  numeric,
  jsonb,
  pgEnum,
} from '@payloadcms/db-postgres/drizzle/pg-core'
import { sql, relations } from '@payloadcms/db-postgres/drizzle'
export const enum_users_role = pgEnum('enum_users_role', ['admin', 'user'])
export const enum_invoices_status = pgEnum('enum_invoices_status', [
  'draft',
  'sent',
  'paid',
  'overdue',
  'cancelled',
])
export const enum_quotes_status = pgEnum('enum_quotes_status', [
  'draft',
  'pending',
  'accepted',
  'expired',
])
export const enum_tasks_priority = pgEnum('enum_tasks_priority', ['low', 'medium', 'high'])
export const enum_transactions_method = pgEnum('enum_transactions_method', [
  'stripe',
  'paypal',
  'bank_transfer',
  'cash',
])
export const enum_activity_type = pgEnum('enum_activity_type', [
  'note',
  'invoice_created',
  'quote_created',
  'quote_sent',
  'task_assigned',
  'task_completed',
  'email_sent',
  'status_change',
  'payment_received',
])
export const enum_activity_related_collection = pgEnum('enum_activity_related_collection', [
  'invoices',
  'quotes',
  'tasks',
  'transactions',
])
export const enum_settings_currency = pgEnum('enum_settings_currency', ['MUR', 'USD', 'EUR'])

export const users_sessions = pgTable(
  'users_sessions',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 }),
    expiresAt: timestamp('expires_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }).notNull(),
  },
  (columns) => [
    index('users_sessions_order_idx').on(columns._order),
    index('users_sessions_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [users.id],
      name: 'users_sessions_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const users = pgTable(
  'users',
  {
    id: serial('id').primaryKey(),
    role: enum_users_role('role').notNull().default('user'),
    emailVerified: boolean('email_verified').default(false),
    emailVerificationToken: varchar('email_verification_token'),
    emailVerificationExpires: timestamp('email_verification_expires', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    passwordResetToken: varchar('password_reset_token'),
    passwordResetExpires: timestamp('password_reset_expires', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    email: varchar('email').notNull(),
    resetPasswordToken: varchar('reset_password_token'),
    resetPasswordExpiration: timestamp('reset_password_expiration', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    salt: varchar('salt'),
    hash: varchar('hash'),
    loginAttempts: numeric('login_attempts', { mode: 'number' }).default(0),
    lockUntil: timestamp('lock_until', { mode: 'string', withTimezone: true, precision: 3 }),
  },
  (columns) => [
    index('users_updated_at_idx').on(columns.updatedAt),
    index('users_created_at_idx').on(columns.createdAt),
    uniqueIndex('users_email_idx').on(columns.email),
  ],
)

export const media = pgTable(
  'media',
  {
    id: serial('id').primaryKey(),
    alt: varchar('alt').notNull(),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    url: varchar('url'),
    thumbnailURL: varchar('thumbnail_u_r_l'),
    filename: varchar('filename'),
    mimeType: varchar('mime_type'),
    filesize: numeric('filesize', { mode: 'number' }),
    width: numeric('width', { mode: 'number' }),
    height: numeric('height', { mode: 'number' }),
    focalX: numeric('focal_x', { mode: 'number' }),
    focalY: numeric('focal_y', { mode: 'number' }),
  },
  (columns) => [
    index('media_updated_at_idx').on(columns.updatedAt),
    index('media_created_at_idx').on(columns.createdAt),
    uniqueIndex('media_filename_idx').on(columns.filename),
  ],
)

export const clients_tags = pgTable(
  'clients_tags',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    tag: varchar('tag'),
  },
  (columns) => [
    index('clients_tags_order_idx').on(columns._order),
    index('clients_tags_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [clients.id],
      name: 'clients_tags_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const clients = pgTable(
  'clients',
  {
    id: serial('id').primaryKey(),
    name: varchar('name').notNull(),
    company: varchar('company'),
    email: varchar('email').notNull(),
    phone: varchar('phone'),
    address: varchar('address'),
    socials_twitter: varchar('socials_twitter'),
    socials_linkedin: varchar('socials_linkedin'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('clients_updated_at_idx').on(columns.updatedAt),
    index('clients_created_at_idx').on(columns.createdAt),
  ],
)

export const invoices_items = pgTable(
  'invoices_items',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    description: varchar('description').notNull(),
    quantity: numeric('quantity', { mode: 'number' }).notNull().default(1),
    rate: numeric('rate', { mode: 'number' }).notNull().default(0),
  },
  (columns) => [
    index('invoices_items_order_idx').on(columns._order),
    index('invoices_items_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [invoices.id],
      name: 'invoices_items_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const invoices = pgTable(
  'invoices',
  {
    id: serial('id').primaryKey(),
    invoiceNumber: varchar('invoice_number').notNull(),
    client: integer('client_id')
      .notNull()
      .references(() => clients.id, {
        onDelete: 'set null',
      }),
    date: timestamp('date', { mode: 'string', withTimezone: true, precision: 3 }).notNull(),
    dueDate: timestamp('due_date', { mode: 'string', withTimezone: true, precision: 3 }).notNull(),
    status: enum_invoices_status('status').notNull().default('draft'),
    taxRate: numeric('tax_rate', { mode: 'number' }).default(0),
    discount: numeric('discount', { mode: 'number' }).default(0),
    shipping: numeric('shipping', { mode: 'number' }).default(0),
    carNumber: varchar('car_number'),
    notes: varchar('notes'),
    subtotal: numeric('subtotal', { mode: 'number' }).notNull().default(0),
    tax: numeric('tax', { mode: 'number' }).notNull().default(0),
    total: numeric('total', { mode: 'number' }).notNull().default(0),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex('invoices_invoice_number_idx').on(columns.invoiceNumber),
    index('invoices_client_idx').on(columns.client),
    index('invoices_updated_at_idx').on(columns.updatedAt),
    index('invoices_created_at_idx').on(columns.createdAt),
  ],
)

export const quotes_items = pgTable(
  'quotes_items',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    description: varchar('description').notNull(),
    quantity: numeric('quantity', { mode: 'number' }).notNull().default(1),
    rate: numeric('rate', { mode: 'number' }).notNull().default(0),
  },
  (columns) => [
    index('quotes_items_order_idx').on(columns._order),
    index('quotes_items_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [quotes.id],
      name: 'quotes_items_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const quotes = pgTable(
  'quotes',
  {
    id: serial('id').primaryKey(),
    quoteNumber: varchar('quote_number').notNull(),
    client: integer('client_id')
      .notNull()
      .references(() => clients.id, {
        onDelete: 'set null',
      }),
    date: timestamp('date', { mode: 'string', withTimezone: true, precision: 3 }).notNull(),
    status: enum_quotes_status('status').notNull().default('pending'),
    total: numeric('total', { mode: 'number' }).notNull().default(0),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('quotes_client_idx').on(columns.client),
    index('quotes_updated_at_idx').on(columns.updatedAt),
    index('quotes_created_at_idx').on(columns.createdAt),
  ],
)

export const tasks = pgTable(
  'tasks',
  {
    id: serial('id').primaryKey(),
    title: varchar('title').notNull(),
    dueDate: timestamp('due_date', { mode: 'string', withTimezone: true, precision: 3 }),
    priority: enum_tasks_priority('priority').default('medium'),
    client: integer('client_id').references(() => clients.id, {
      onDelete: 'set null',
    }),
    completed: boolean('completed').default(false),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('tasks_client_idx').on(columns.client),
    index('tasks_updated_at_idx').on(columns.updatedAt),
    index('tasks_created_at_idx').on(columns.createdAt),
  ],
)

export const transactions = pgTable(
  'transactions',
  {
    id: serial('id').primaryKey(),
    date: timestamp('date', { mode: 'string', withTimezone: true, precision: 3 }).notNull(),
    amount: numeric('amount', { mode: 'number' }).notNull(),
    client: integer('client_id')
      .notNull()
      .references(() => clients.id, {
        onDelete: 'set null',
      }),
    reference: varchar('reference'),
    method: enum_transactions_method('method').default('stripe'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('transactions_client_idx').on(columns.client),
    index('transactions_updated_at_idx').on(columns.updatedAt),
    index('transactions_created_at_idx').on(columns.createdAt),
  ],
)

export const activity = pgTable(
  'activity',
  {
    id: serial('id').primaryKey(),
    client: integer('client_id')
      .notNull()
      .references(() => clients.id, {
        onDelete: 'set null',
      }),
    type: enum_activity_type('type').notNull().default('note'),
    body: varchar('body'),
    relatedCollection: enum_activity_related_collection('related_collection'),
    relatedId: numeric('related_id', { mode: 'number' }),
    meta: jsonb('meta'),
    createdBy: integer('created_by_id').references(() => users.id, {
      onDelete: 'set null',
    }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('activity_client_idx').on(columns.client),
    index('activity_created_by_idx').on(columns.createdBy),
    index('activity_updated_at_idx').on(columns.updatedAt),
    index('activity_created_at_idx').on(columns.createdAt),
  ],
)

export const payload_kv = pgTable(
  'payload_kv',
  {
    id: serial('id').primaryKey(),
    key: varchar('key').notNull(),
    data: jsonb('data').notNull(),
  },
  (columns) => [uniqueIndex('payload_kv_key_idx').on(columns.key)],
)

export const payload_locked_documents = pgTable(
  'payload_locked_documents',
  {
    id: serial('id').primaryKey(),
    globalSlug: varchar('global_slug'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('payload_locked_documents_global_slug_idx').on(columns.globalSlug),
    index('payload_locked_documents_updated_at_idx').on(columns.updatedAt),
    index('payload_locked_documents_created_at_idx').on(columns.createdAt),
  ],
)

export const payload_locked_documents_rels = pgTable(
  'payload_locked_documents_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    usersID: integer('users_id'),
    mediaID: integer('media_id'),
    clientsID: integer('clients_id'),
    invoicesID: integer('invoices_id'),
    quotesID: integer('quotes_id'),
    tasksID: integer('tasks_id'),
    transactionsID: integer('transactions_id'),
    activityID: integer('activity_id'),
  },
  (columns) => [
    index('payload_locked_documents_rels_order_idx').on(columns.order),
    index('payload_locked_documents_rels_parent_idx').on(columns.parent),
    index('payload_locked_documents_rels_path_idx').on(columns.path),
    index('payload_locked_documents_rels_users_id_idx').on(columns.usersID),
    index('payload_locked_documents_rels_media_id_idx').on(columns.mediaID),
    index('payload_locked_documents_rels_clients_id_idx').on(columns.clientsID),
    index('payload_locked_documents_rels_invoices_id_idx').on(columns.invoicesID),
    index('payload_locked_documents_rels_quotes_id_idx').on(columns.quotesID),
    index('payload_locked_documents_rels_tasks_id_idx').on(columns.tasksID),
    index('payload_locked_documents_rels_transactions_id_idx').on(columns.transactionsID),
    index('payload_locked_documents_rels_activity_id_idx').on(columns.activityID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [payload_locked_documents.id],
      name: 'payload_locked_documents_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['usersID']],
      foreignColumns: [users.id],
      name: 'payload_locked_documents_rels_users_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['mediaID']],
      foreignColumns: [media.id],
      name: 'payload_locked_documents_rels_media_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['clientsID']],
      foreignColumns: [clients.id],
      name: 'payload_locked_documents_rels_clients_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['invoicesID']],
      foreignColumns: [invoices.id],
      name: 'payload_locked_documents_rels_invoices_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['quotesID']],
      foreignColumns: [quotes.id],
      name: 'payload_locked_documents_rels_quotes_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['tasksID']],
      foreignColumns: [tasks.id],
      name: 'payload_locked_documents_rels_tasks_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['transactionsID']],
      foreignColumns: [transactions.id],
      name: 'payload_locked_documents_rels_transactions_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['activityID']],
      foreignColumns: [activity.id],
      name: 'payload_locked_documents_rels_activity_fk',
    }).onDelete('cascade'),
  ],
)

export const payload_preferences = pgTable(
  'payload_preferences',
  {
    id: serial('id').primaryKey(),
    key: varchar('key'),
    value: jsonb('value'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('payload_preferences_key_idx').on(columns.key),
    index('payload_preferences_updated_at_idx').on(columns.updatedAt),
    index('payload_preferences_created_at_idx').on(columns.createdAt),
  ],
)

export const payload_preferences_rels = pgTable(
  'payload_preferences_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    usersID: integer('users_id'),
  },
  (columns) => [
    index('payload_preferences_rels_order_idx').on(columns.order),
    index('payload_preferences_rels_parent_idx').on(columns.parent),
    index('payload_preferences_rels_path_idx').on(columns.path),
    index('payload_preferences_rels_users_id_idx').on(columns.usersID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [payload_preferences.id],
      name: 'payload_preferences_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['usersID']],
      foreignColumns: [users.id],
      name: 'payload_preferences_rels_users_fk',
    }).onDelete('cascade'),
  ],
)

export const payload_migrations = pgTable(
  'payload_migrations',
  {
    id: serial('id').primaryKey(),
    name: varchar('name'),
    batch: numeric('batch', { mode: 'number' }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('payload_migrations_updated_at_idx').on(columns.updatedAt),
    index('payload_migrations_created_at_idx').on(columns.createdAt),
  ],
)

export const settings = pgTable('settings', {
  id: serial('id').primaryKey(),
  businessName: varchar('business_name').notNull().default(''),
  businessAddress: varchar('business_address').default(''),
  businessEmail: varchar('business_email').default(''),
  businessPhone: varchar('business_phone').default(''),
  businessWebsite: varchar('business_website').default(''),
  logoUrl: varchar('logo_url'),
  invoicePrefix: varchar('invoice_prefix').default('INV-'),
  taxRateDefault: numeric('tax_rate_default', { mode: 'number' }).default(0),
  currency: enum_settings_currency('currency').default('MUR'),
  updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 }),
  createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 }),
})

export const relations_users_sessions = relations(users_sessions, ({ one }) => ({
  _parentID: one(users, {
    fields: [users_sessions._parentID],
    references: [users.id],
    relationName: 'sessions',
  }),
}))
export const relations_users = relations(users, ({ many }) => ({
  sessions: many(users_sessions, {
    relationName: 'sessions',
  }),
}))
export const relations_media = relations(media, () => ({}))
export const relations_clients_tags = relations(clients_tags, ({ one }) => ({
  _parentID: one(clients, {
    fields: [clients_tags._parentID],
    references: [clients.id],
    relationName: 'tags',
  }),
}))
export const relations_clients = relations(clients, ({ many }) => ({
  tags: many(clients_tags, {
    relationName: 'tags',
  }),
}))
export const relations_invoices_items = relations(invoices_items, ({ one }) => ({
  _parentID: one(invoices, {
    fields: [invoices_items._parentID],
    references: [invoices.id],
    relationName: 'items',
  }),
}))
export const relations_invoices = relations(invoices, ({ one, many }) => ({
  client: one(clients, {
    fields: [invoices.client],
    references: [clients.id],
    relationName: 'client',
  }),
  items: many(invoices_items, {
    relationName: 'items',
  }),
}))
export const relations_quotes_items = relations(quotes_items, ({ one }) => ({
  _parentID: one(quotes, {
    fields: [quotes_items._parentID],
    references: [quotes.id],
    relationName: 'items',
  }),
}))
export const relations_quotes = relations(quotes, ({ one, many }) => ({
  client: one(clients, {
    fields: [quotes.client],
    references: [clients.id],
    relationName: 'client',
  }),
  items: many(quotes_items, {
    relationName: 'items',
  }),
}))
export const relations_tasks = relations(tasks, ({ one }) => ({
  client: one(clients, {
    fields: [tasks.client],
    references: [clients.id],
    relationName: 'client',
  }),
}))
export const relations_transactions = relations(transactions, ({ one }) => ({
  client: one(clients, {
    fields: [transactions.client],
    references: [clients.id],
    relationName: 'client',
  }),
}))
export const relations_activity = relations(activity, ({ one }) => ({
  client: one(clients, {
    fields: [activity.client],
    references: [clients.id],
    relationName: 'client',
  }),
  createdBy: one(users, {
    fields: [activity.createdBy],
    references: [users.id],
    relationName: 'createdBy',
  }),
}))
export const relations_payload_kv = relations(payload_kv, () => ({}))
export const relations_payload_locked_documents_rels = relations(
  payload_locked_documents_rels,
  ({ one }) => ({
    parent: one(payload_locked_documents, {
      fields: [payload_locked_documents_rels.parent],
      references: [payload_locked_documents.id],
      relationName: '_rels',
    }),
    usersID: one(users, {
      fields: [payload_locked_documents_rels.usersID],
      references: [users.id],
      relationName: 'users',
    }),
    mediaID: one(media, {
      fields: [payload_locked_documents_rels.mediaID],
      references: [media.id],
      relationName: 'media',
    }),
    clientsID: one(clients, {
      fields: [payload_locked_documents_rels.clientsID],
      references: [clients.id],
      relationName: 'clients',
    }),
    invoicesID: one(invoices, {
      fields: [payload_locked_documents_rels.invoicesID],
      references: [invoices.id],
      relationName: 'invoices',
    }),
    quotesID: one(quotes, {
      fields: [payload_locked_documents_rels.quotesID],
      references: [quotes.id],
      relationName: 'quotes',
    }),
    tasksID: one(tasks, {
      fields: [payload_locked_documents_rels.tasksID],
      references: [tasks.id],
      relationName: 'tasks',
    }),
    transactionsID: one(transactions, {
      fields: [payload_locked_documents_rels.transactionsID],
      references: [transactions.id],
      relationName: 'transactions',
    }),
    activityID: one(activity, {
      fields: [payload_locked_documents_rels.activityID],
      references: [activity.id],
      relationName: 'activity',
    }),
  }),
)
export const relations_payload_locked_documents = relations(
  payload_locked_documents,
  ({ many }) => ({
    _rels: many(payload_locked_documents_rels, {
      relationName: '_rels',
    }),
  }),
)
export const relations_payload_preferences_rels = relations(
  payload_preferences_rels,
  ({ one }) => ({
    parent: one(payload_preferences, {
      fields: [payload_preferences_rels.parent],
      references: [payload_preferences.id],
      relationName: '_rels',
    }),
    usersID: one(users, {
      fields: [payload_preferences_rels.usersID],
      references: [users.id],
      relationName: 'users',
    }),
  }),
)
export const relations_payload_preferences = relations(payload_preferences, ({ many }) => ({
  _rels: many(payload_preferences_rels, {
    relationName: '_rels',
  }),
}))
export const relations_payload_migrations = relations(payload_migrations, () => ({}))
export const relations_settings = relations(settings, () => ({}))

type DatabaseSchema = {
  enum_users_role: typeof enum_users_role
  enum_invoices_status: typeof enum_invoices_status
  enum_quotes_status: typeof enum_quotes_status
  enum_tasks_priority: typeof enum_tasks_priority
  enum_transactions_method: typeof enum_transactions_method
  enum_activity_type: typeof enum_activity_type
  enum_activity_related_collection: typeof enum_activity_related_collection
  enum_settings_currency: typeof enum_settings_currency
  users_sessions: typeof users_sessions
  users: typeof users
  media: typeof media
  clients_tags: typeof clients_tags
  clients: typeof clients
  invoices_items: typeof invoices_items
  invoices: typeof invoices
  quotes_items: typeof quotes_items
  quotes: typeof quotes
  tasks: typeof tasks
  transactions: typeof transactions
  activity: typeof activity
  payload_kv: typeof payload_kv
  payload_locked_documents: typeof payload_locked_documents
  payload_locked_documents_rels: typeof payload_locked_documents_rels
  payload_preferences: typeof payload_preferences
  payload_preferences_rels: typeof payload_preferences_rels
  payload_migrations: typeof payload_migrations
  settings: typeof settings
  relations_users_sessions: typeof relations_users_sessions
  relations_users: typeof relations_users
  relations_media: typeof relations_media
  relations_clients_tags: typeof relations_clients_tags
  relations_clients: typeof relations_clients
  relations_invoices_items: typeof relations_invoices_items
  relations_invoices: typeof relations_invoices
  relations_quotes_items: typeof relations_quotes_items
  relations_quotes: typeof relations_quotes
  relations_tasks: typeof relations_tasks
  relations_transactions: typeof relations_transactions
  relations_activity: typeof relations_activity
  relations_payload_kv: typeof relations_payload_kv
  relations_payload_locked_documents_rels: typeof relations_payload_locked_documents_rels
  relations_payload_locked_documents: typeof relations_payload_locked_documents
  relations_payload_preferences_rels: typeof relations_payload_preferences_rels
  relations_payload_preferences: typeof relations_payload_preferences
  relations_payload_migrations: typeof relations_payload_migrations
  relations_settings: typeof relations_settings
}

declare module '@payloadcms/db-postgres' {
  export interface GeneratedDatabaseSchema {
    schema: DatabaseSchema
  }
}
